export type PriceType = "fixed" | "from" | "variable";
export type UrgencyLevel = "normal" | "priority" | "emergency";

export type DentalServiceDefinition = {
  id: string;
  name: string;
  aliases: string[];
  category: string;
  priceType: PriceType;
  requiresEvaluation: boolean;
  variablePriceReason: string;
  defaultDurationMinutes: number;
  evaluationServiceId: string;
  recommendedCTA: string;
  urgencyLevel: UrgencyLevel;
};

export const DENTAL_SERVICES_CATALOG: DentalServiceDefinition[] = [
  {
    id: "evaluation",
    name: "Evaluación",
    aliases: ["evaluacion", "evaluación", "consulta", "revision", "revisión", "valoracion", "valoración"],
    category: "diagnostico",
    priceType: "fixed",
    requiresEvaluation: false,
    variablePriceReason: "",
    defaultDurationMinutes: 30,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés que te ayude a agendar la evaluación?",
    urgencyLevel: "normal",
  },
  {
    id: "cleaning",
    name: "Limpieza dental",
    aliases: ["limpieza", "limpieza dental", "profilaxis", "cleaning"],
    category: "preventivo",
    priceType: "from",
    requiresEvaluation: false,
    variablePriceReason: "depende de si se requiere limpieza básica o limpieza profunda.",
    defaultDurationMinutes: 45,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés que revisemos horarios para limpieza dental?",
    urgencyLevel: "normal",
  },
  {
    id: "deep_cleaning",
    name: "Limpieza profunda",
    aliases: ["limpieza profunda", "periodontal", "deep cleaning"],
    category: "periodoncia",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende del estado de las encías y la acumulación de sarro.",
    defaultDurationMinutes: 60,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés agendar una evaluación para definir el plan?",
    urgencyLevel: "priority",
  },
  {
    id: "whitening",
    name: "Blanqueamiento dental",
    aliases: ["blanqueamiento", "blanqueamiento dental", "whitening", "blanqueo"],
    category: "estetico",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende de la evaluación, la sensibilidad y el tipo de blanqueamiento.",
    defaultDurationMinutes: 60,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Te ayudo a agendar una evaluación para blanqueamiento?",
    urgencyLevel: "normal",
  },
  {
    id: "orthodontics",
    name: "Ortodoncia / brackets",
    aliases: ["ortodoncia", "brackets", "frenillos", "frenillo", "braces"],
    category: "ortodoncia",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende de la posición de los dientes, el tipo de tratamiento y el tiempo estimado.",
    defaultDurationMinutes: 45,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés que te ayude a agendar una evaluación de ortodoncia?",
    urgencyLevel: "normal",
  },
  {
    id: "fillings",
    name: "Resinas / empastes",
    aliases: ["resina", "resinas", "empaste", "empastes", "calza", "relleno"],
    category: "restaurador",
    priceType: "from",
    requiresEvaluation: true,
    variablePriceReason: "depende del tamaño de la restauración y la pieza dental.",
    defaultDurationMinutes: 45,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés que revisemos horarios para evaluación?",
    urgencyLevel: "normal",
  },
  {
    id: "simple_extraction",
    name: "Extracción simple",
    aliases: ["extraccion", "extracción", "sacar muela", "muela"],
    category: "quirurgico",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende de si es simple o quirúrgica, el estado de la muela y si hay inflamación o infección.",
    defaultDurationMinutes: 50,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Te ayudo a agendar una evaluación para extracción?",
    urgencyLevel: "priority",
  },
  {
    id: "wisdom_tooth_extraction",
    name: "Extracción de cordales",
    aliases: ["cordales", "muela del juicio", "extraccion de cordales", "extracción de cordales"],
    category: "quirurgico",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende de la posición de la cordal, si está retenida y el nivel de complejidad quirúrgica.",
    defaultDurationMinutes: 70,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés que agendemos evaluación con radiografía?",
    urgencyLevel: "priority",
  },
  {
    id: "endodontics",
    name: "Endodoncia",
    aliases: ["endodoncia", "root canal", "tratamiento de conducto", "nervio"],
    category: "restaurador",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende del diente, la cantidad de conductos y si hay infección.",
    defaultDurationMinutes: 75,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Te ayudo a agendar evaluación para endodoncia?",
    urgencyLevel: "priority",
  },
  {
    id: "implants",
    name: "Implantes",
    aliases: ["implante", "implantes", "implants"],
    category: "rehabilitacion",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende del estado del hueso, el tipo de implante y el plan indicado.",
    defaultDurationMinutes: 60,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés agendar una evaluación para implantes?",
    urgencyLevel: "normal",
  },
  {
    id: "veneers",
    name: "Carillas",
    aliases: ["carillas", "veneers", "diseño de sonrisa", "diseno de sonrisa"],
    category: "estetico",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende del material, la cantidad de piezas y el resultado que se busca.",
    defaultDurationMinutes: 60,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés agendar una evaluación estética?",
    urgencyLevel: "normal",
  },
  {
    id: "crowns",
    name: "Coronas",
    aliases: ["corona", "coronas"],
    category: "rehabilitacion",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende del material, cantidad de piezas y evaluación del caso.",
    defaultDurationMinutes: 60,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Te ayudo a agendar una evaluación para coronas?",
    urgencyLevel: "normal",
  },
  {
    id: "bridges",
    name: "Puentes",
    aliases: ["puente", "puentes"],
    category: "rehabilitacion",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende del material, cantidad de piezas y evaluación del caso.",
    defaultDurationMinutes: 60,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés revisar horarios para evaluación de puentes?",
    urgencyLevel: "normal",
  },
  {
    id: "dentures",
    name: "Prótesis",
    aliases: ["protesis", "prótesis", "placa dental", "dentures"],
    category: "rehabilitacion",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende del material, cantidad de piezas y evaluación del caso.",
    defaultDurationMinutes: 60,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés agendar una evaluación para prótesis?",
    urgencyLevel: "normal",
  },
  {
    id: "emergency",
    name: "Urgencia dental",
    aliases: ["urgencia", "emergencia", "dolor", "infeccion", "infección"],
    category: "urgencia",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende del diagnóstico inmediato y el procedimiento necesario para estabilizar el caso.",
    defaultDurationMinutes: 30,
    evaluationServiceId: "evaluation",
    recommendedCTA: "Te ayudo a priorizar una cita lo antes posible.",
    urgencyLevel: "emergency",
  },
  {
    id: "pediatric_dentistry",
    name: "Odontopediatría",
    aliases: ["odontopediatria", "odontopediatría", "pediatrico", "niños", "ninos"],
    category: "pediatrico",
    priceType: "from",
    requiresEvaluation: true,
    variablePriceReason: "depende de la edad, el diagnóstico y el procedimiento indicado.",
    defaultDurationMinutes: 40,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés que revisemos horarios para odontopediatría?",
    urgencyLevel: "normal",
  },
  {
    id: "periodontics",
    name: "Periodoncia",
    aliases: ["periodoncia", "encias", "encías", "gingivitis"],
    category: "periodoncia",
    priceType: "variable",
    requiresEvaluation: true,
    variablePriceReason: "depende del estado de las encías y la acumulación de sarro.",
    defaultDurationMinutes: 50,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés agendar una evaluación periodontal?",
    urgencyLevel: "priority",
  },
  {
    id: "xray",
    name: "Radiografía dental",
    aliases: ["radiografia", "radiografía", "rayos x", "xray"],
    category: "diagnostico",
    priceType: "fixed",
    requiresEvaluation: false,
    variablePriceReason: "",
    defaultDurationMinutes: 20,
    evaluationServiceId: "evaluation",
    recommendedCTA: "¿Querés que te ayude a agendar la radiografía?",
    urgencyLevel: "normal",
  },
];

export function getDentalServiceById(serviceId: string): DentalServiceDefinition | null {
  return DENTAL_SERVICES_CATALOG.find((service) => service.id === serviceId) ?? null;
}
