import { useCallback, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import CouponScanner from "../../components/referral/CouponScanner";
import { lookupCoupon, parseCouponToken, redeemCoupon, type StaffCoupon } from "../../referral/coupons";

const LABEL={valid:"Cupón válido",redeemed:"Cupón ya utilizado",expired:"Cupón vencido",invalid:"Cupón no válido",forbidden:"No tienes permiso para canjear este cupón"} as const;
export default function CouponValidator(){const {publicToken}=useParams();const [lookup,setLookup]=useState(publicToken??"");const [coupon,setCoupon]=useState<StaffCoupon|null>(null);const [total,setTotal]=useState("");const [location,setLocation]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const validate=useCallback(async(value:string)=>{setBusy(true);setError("");try{const token=parseCouponToken(value);setLookup(token);setCoupon(await lookupCoupon(token));}catch{setError("No se pudo validar el cupón.");}finally{setBusy(false);}},[]);
  useEffect(()=>{if(publicToken)void validate(publicToken);},[publicToken,validate]);
  async function redeem(){if(!coupon?.coupon_id||coupon.result!=="valid")return;const cents=Math.round(Number(total)*100);if(!Number.isFinite(cents)||cents<0||!location.trim()){setError("Ingresa el total y la ubicación.");return;}if(!window.confirm("¿Confirmas el canje de este cupón? Esta acción no se puede repetir."))return;setBusy(true);try{const out=await redeemCoupon(coupon.coupon_id,cents,location);setCoupon({...coupon,result:out.result});}catch{setError("No se pudo canjear el cupón.");}finally{setBusy(false);}}
  return <main className="referral-page"><header><p className="coupon-eyebrow">Referral Hub</p><h1 className="text-2xl font-black">Validar cupón</h1><p className="text-sm text-[#7E8C99]">Escanea el QR o escribe el código de respaldo.</p></header><section className="coupon-validator-card"><CouponScanner onScan={(value)=>void validate(value)}/><div className="flex gap-2"><input value={lookup} onChange={e=>setLookup(e.target.value)} placeholder="SUPER20-XXXXXXXX" className="coupon-input"/><button disabled={busy} onClick={()=>void validate(lookup)} className="coupon-secondary">Validar</button></div>{error?<p className="text-sm text-red-300">{error}</p>:null}{coupon?<div className="space-y-3 rounded-2xl bg-white/[.04] p-4"><strong>{LABEL[coupon.result]}</strong>{coupon.campaign_name?<p>{coupon.campaign_name} · ${(Number(coupon.discount_cents)/100).toFixed(0)}</p>:null}{coupon.expires_at?<p>Vence {new Date(coupon.expires_at).toLocaleDateString("es-US")}</p>:null}{coupon.result==="valid"?<><input type="number" min="0" step="0.01" value={total} onChange={e=>setTotal(e.target.value)} placeholder="Total de la compra" className="coupon-input"/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Sucursal o ubicación" className="coupon-input"/><button disabled={busy} onClick={()=>void redeem()} className="coupon-primary">Canjear cupón</button></>:null}</div>:null}</section></main>}
