import { ArrowLeft, Bot, CheckCircle2, Clock3, ExternalLink, MapPin, RotateCcw, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { MobileEmptyState, MobileHeader, MobileStatusPill } from "../../components/mobile/MobilePrimitives";
import { ReferralPartnerSheet } from "../../components/referral/ReferralPartnerSheet";
import { ReferralServiceIcon } from "../../components/referral/ReferralLeadCard";
import { ReferralStatusSheet } from "../../components/referral/ReferralStatusSheet";
import { ReferralStickyActions } from "../../components/referral/ReferralStickyActions";
import { leadLocation, leadName, leadPhone, leadSource, normalizeReferralStatus, publicPartnerName, relativeAge, serviceName, statusLabel, statusTone } from "../../referral/status";
import { useReferralData } from "../../referral/useReferralData";
import type { ReferralStatus } from "../../referral/types";
import { ReferralLoading } from "./ReferralHome";

export default function ReferralLeadDetail() {
  const { leadId } = useParams(); const navigate = useNavigate(); const data = useReferralData();
  const [partnerOpen, setPartnerOpen] = useState(false); const [statusOpen, setStatusOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const lead = data.leads.find((item) => item.id === leadId);
  const service = lead?.service_id ? data.services[lead.service_id] : undefined;
  const partner = lead?.partner_recomendado ? data.partners[lead.partner_recomendado] : undefined;
  const partnerOptions = useMemo(() => !lead?.service_id ? [] : Object.values(data.partners).filter((item) => Array.isArray(item.servicios) && item.servicios.includes(lead.service_id!)), [data.partners, lead?.service_id]);
  if (data.loading) return <ReferralLoading />;
  if (!lead || lead.organization_id !== data.organizationId) return <main className="referral-page"><MobileEmptyState title="Lead no encontrado" description="No existe o no pertenece a esta organización." /></main>;
  const activeLead = lead;
  const status = normalizeReferralStatus(activeLead.status); const phone = leadPhone(activeLead); const location = leadLocation(activeLead); const source = leadSource(activeLead); const answers = Object.entries(activeLead.extracted_data ?? {}).filter(([, value]) => value !== null && value !== undefined && value !== "");
  const primary = status === "new" ? { label: "Contactar lead", action: () => openContact("whatsapp") } : status === "contacted" ? { label: "Calificar", action: () => navigate(`/leads/${lead.id}/qualify`) } : status === "qualified" && !lead.partner_recomendado ? { label: "Asignar aliado", action: () => setPartnerOpen(true) } : { label: "Mover etapa", action: () => setStatusOpen(true) };
  function openContact(kind: "call" | "whatsapp") { const clean = phone.replace(/[^\d+]/g, "").replace(/^\+/, ""); if (!clean) { setMessage("Este lead no tiene teléfono disponible."); return; } window.open(kind === "call" ? `tel:${clean}` : `https://wa.me/${clean}`, "_blank", "noopener,noreferrer"); }
  async function changeStatus(next: ReferralStatus) { setBusy(true); const result = await data.updateStatus(activeLead.id, next); setBusy(false); if (result.ok) { setStatusOpen(false); setMessage("Estado actualizado."); } else setMessage(result.message ?? "No se pudo actualizar."); }
  async function assign(partnerId: string) { setBusy(true); const result = await data.assignPartner(activeLead, partnerId); setBusy(false); if (result.ok) { setPartnerOpen(false); setMessage("Aliado asignado y lead actualizado."); } else { setMessage(result.message ?? "No se pudo asignar."); if (!result.partial) setPartnerOpen(true); } }
  return <main className="referral-page referral-page-with-actions"><button type="button" className="referral-back" onClick={() => navigate("/leads")}><ArrowLeft className="h-4 w-4" />Leads</button>
    <MobileHeader eyebrow={serviceName(service)} title={leadName(lead)} subtitle={`${relativeAge(lead.created_at)} · ${statusLabel(status)}`} action={<MobileStatusPill tone={statusTone[status]} className={`referral-status-pill referral-pill-${statusTone[status]}`}>{statusLabel(status)}</MobileStatusPill>} />
    {(message || data.syncWarning?.leadId === lead.id) ? <div className={data.syncWarning?.leadId === lead.id ? "referral-warning" : "referral-success"}><p>{message ?? "La asignación existe, pero falta sincronizar el lead."}</p>{data.syncWarning?.leadId === lead.id ? <button onClick={async () => { setBusy(true); const result = await data.retryAssignmentSync(); setBusy(false); setMessage(result.ok ? "Sincronización completada." : result.message ?? "No se pudo sincronizar."); }}><RotateCcw className="h-3.5 w-3.5" />Reintentar sincronización</button> : null}</div> : null}
    <section className="referral-identity-card"><div className="referral-service-icon large"><ReferralServiceIcon service={service} className="h-6 w-6" /></div><div className="min-w-0 flex-1"><h2>{serviceName(service)}</h2>{phone ? <p>{phone}</p> : <p>Sin teléfono disponible</p>}{(location || source) ? <div className="mt-2 flex flex-wrap gap-2">{location ? <span><MapPin className="h-3 w-3" />{location}</span> : null}{source ? <span><ExternalLink className="h-3 w-3" />{source}</span> : null}</div> : null}</div></section>
    {(lead.resumen_auto || lead.recomendacion) ? <section className="referral-panel referral-elevated"><p className="referral-eyebrow"><Bot className="mr-1 inline h-3.5 w-3.5" />Apoyo inteligente</p>{lead.resumen_auto ? <div className="mt-3"><h2>Resumen</h2><p className="referral-body-copy">{lead.resumen_auto}</p></div> : null}{lead.recomendacion ? <div className="mt-4 border-t border-white/[0.04] pt-4"><h2><Sparkles className="mr-1 inline h-4 w-4 text-[#7AA2FF]" />Recomendación</h2><p className="referral-body-copy">{lead.recomendacion}</p></div> : null}</section> : null}
    <section className="referral-panel"><div className="referral-section-heading"><div><p className="referral-eyebrow">Intake</p><h2>Respuestas recopiladas</h2></div><span>{answers.length}</span></div>{answers.length ? <div className="divide-y divide-white/[0.06]">{answers.map(([key, value]) => <div key={key} className="py-3"><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-[#748291]">{key.replace(/_/g, " ")}</p><p className="mt-1 break-words text-sm leading-6 text-[#EAF0F5]">{typeof value === "object" ? JSON.stringify(value) : String(value)}</p></div>)}</div> : <p className="referral-body-copy">Aún no hay respuestas capturadas.</p>}</section>
    <section className="referral-panel"><p className="referral-eyebrow">Asignación</p><div className="mt-3 flex items-center justify-between gap-3"><div><h2>{publicPartnerName(partner?.nombre) || "Sin aliado asignado"}</h2><p className="mt-1 text-xs text-[#748291]">{partner ? "Asignación actual" : "Este lead todavía necesita un aliado"}</p></div>{partner ? <CheckCircle2 className="h-5 w-5 text-[#22C55E]" /> : <button className="referral-text-button" onClick={() => setPartnerOpen(true)}>Asignar</button>}</div></section>
    <section className="referral-panel"><p className="referral-eyebrow">Actividad verificable</p><div className="mt-3 space-y-3"><div className="referral-activity"><Clock3 className="h-4 w-4" /><div><strong>Lead recibido</strong><span>{lead.created_at ? new Date(lead.created_at).toLocaleString("es", { dateStyle: "medium", timeStyle: "short" }) : "Fecha no disponible"}</span></div></div>{lead.updated_at && lead.updated_at !== lead.created_at ? <div className="referral-activity"><CheckCircle2 className="h-4 w-4" /><div><strong>Última actualización · {statusLabel(status)}</strong><span>{new Date(lead.updated_at).toLocaleString("es", { dateStyle: "medium", timeStyle: "short" })}</span></div></div> : null}</div></section>
    <ReferralStickyActions primaryLabel={primary.label} phone={phone} onPrimary={primary.action} onCall={() => openContact("call")} onWhatsApp={() => openContact("whatsapp")} onMore={() => setStatusOpen(true)} />
    <ReferralPartnerSheet open={partnerOpen} partners={partnerOptions} service={service} selectedId={lead.partner_recomendado} busy={busy} onClose={() => setPartnerOpen(false)} onConfirm={(id) => void assign(id)} />
    <ReferralStatusSheet open={statusOpen} current={lead.status} busy={busy} onClose={() => setStatusOpen(false)} onSelect={(next) => void changeStatus(next)} />
  </main>;
}
